### ISSUE TITLE
UI and API development for the Trading Time Tokenisation Engine 

### ISSUE THREAD

**Issue by gokulsan** [aeternity/bounties#3]
## Introduction

Aeon Network is the Hash Time Lock based implementation of Trading Time Tokenisation Engine for Derivatives, Futures and other advanced financial primitives. Aeon Network is envisioning a seamless and secure trading experience in across various crypto currencies such as Bitcoin, Ethereum, Binance, Harmony, etc. 

## Goal

In order to complete deployment of these crypto economic and crypto financial components, a well defined user experience and user engagement is necessary. Hence we are looking for a team of talented UI and API developers to join hands with us in the development of UI and API components and complete the integration with a set of smart contracts written on Sophia, a functional programming language. 

## Requirements

- Develop the UI components in VueJS, or ReactJS
- Integrate the UI with the backend on NodeJS
- Deploy the UI and API components on TestNet
- Write security testing scripts for UI and APIs
- Write performance testing scripts for UI and APIs
- Integrate with the SuperHero Wallet
- Provide meaningful README(s)
- Publish the source-code under ISC License
- Publish a video how to use the application

**Comment by marc0olo** [comment]
we only handle bounties defined by the team here at the moment. closing for now
