### ISSUE TITLE
React Boilerplate

### ISSUE THREAD

**Issue by kenodressel** [aeternity/bounties#4]
Hey Community!

This is our bounty to create a react boilerplate. We want to keep the added noise minimal which is why we only want a working SDK integration at the moment. We might want to expand this further in the future but this should serve as a baseline.

- [x] use the latest https://github.com/facebook/create-react-app as a baseline
- [x] add the latest version https://github.com/aeternity/aepp-sdk-js/ as a dependency
- [x] create a wrapper hook `const [client, clientReady] = useAeternitySDK()` that connects to the superhero wallet
- [x] print the current address & balance in the console

To claim this bounty please comment here in the issue and provide a timeline.

More details regarding the hook:
- It should export the universal stamp as `client`
- It should have `clientReady` to `true` once the sdk is fully initialized

**Comment by emmanuelJet** [comment]
@kenodressel, I would love to take care of this bounty. My estimated date of completion is November 10th, 2021.

However, am I to create a 'aepp-boilerplate-react' public template?

**Comment by kenodressel** [comment]
Create it under your own account. We will then import it to the aeternity org.

**Comment by emmanuelJet** [comment]
> Create it under your own account. We will then import it to the aeternity org.

Great I will do just that

**Comment by emmanuelJet** [comment]
@kenodressel, can I proceed?

**Comment by ErkanKanden** [comment]
@emmanuelJet you may proceed :)

**Comment by emmanuelJet** [comment]
I have started the process and completed task 1 at [emmanuelJet/aepp-boilerplate-react](https://github.com/emmanuelJet/aepp-boilerplate-react).

**Comment by emmanuelJet** [comment]
@ErkanKanden, @kenodressel, can I include a deployment GitHub Action using gh-pages?

**Comment by kenodressel** [comment]
please do :)

**Comment by emmanuelJet** [comment]
## Bounty Progress Update

-  I have completed task 2
- I have implemented the GitHub action

> The deployed boilerplate  can be seen via [GitHub Page](https://emmanueljet.github.io/aepp-boilerplate-react)

**Comment by emmanuelJet** [comment]
## Bounty Progress Update

I have completed tasks 3 & 4 following the extra guidelines.

**Quick Links**

- [Repository](https://github.com/emmanuelJet/aepp-boilerplate-react)
- [Live Preview](https://emmanueljet.github.io/aepp-boilerplate-react)

Thanks, furthermore I look forward to reviews.

**Comment by kenodressel** [comment]
I tested and had the following crash:
![image](https://user-images.githubusercontent.com/765921/141451802-f37194c2-ed34-4a02-ab72-ea4a51526a16.png)
![image](https://user-images.githubusercontent.com/765921/141451891-696f790b-b8c8-4ea9-bd39-879966b543a3.png)

**Comment by kenodressel** [comment]
Generally the setup looks nice. Two points

1. I would like the utils/aeternity.js to take care of dispatching the store actions as well, right now you modify the state twice, from the aeternity.js & App.js. Maybe we can reduce that to one.
2. The aeternitySDK function takes the state as an argument but overrides it immediately, that should be fixed as well.

**Comment by emmanuelJet** [comment]
Thanks for the feedback. I would update the codebase as required later today.

**Comment by emmanuelJet** [comment]
Thanks for the feedback. I would update the codebase as required later today.

**Comment by emmanuelJet** [comment]
Happy new week @kenodressel, I have worked on the feedback.

**Comment by kenodressel** [comment]
>  create a wrapper hook const [client, clientReady] = useAeternitySDK() that connects to the superhero wallet

I am still missing something like this...
When I create a new page I would like this to be the only thing I have to add

**Comment by emmanuelJet** [comment]
> I am still missing something like this... When I create a new page I would like this to be the only thing I have to add

I don't quite get this @kenodressel. If one creates a new page, all that is needed would be to get the stored values (sdk, address, and balance) to perform transactions.

I tried making the dispatches happen on aeternity.js but it makes users click the confirm button three times to dispatch client(sdk), connected address, and address balance.

**Comment by emmanuelJet** [comment]
Hello again @kenodressel, I still very much look forward to your feedback.

**Comment by kenodressel** [comment]
Hm I would still like a less store based solution and more functional approach, using the hook it should also be possible to not ask the user 3 times.

**Comment by emmanuelJet** [comment]
Well acknowledged.

**Comment by emmanuelJet** [comment]
Hello @kenodressel,

I have removed all things redux and have made the solution follow a functional approach. The `aeternitySDK()` now returns the `client` to get the address, balance, and perform other methods.

Thanks.

**Comment by kenodressel** [comment]
Sorry I don't think we understand each other. I want a simple reactive hook that I can use. It can use a `useEffect` internally but at the end all that should be exported is a `useAeternitySDK`. Its a minor change from your setup but please do it anyways :)

**Comment by emmanuelJet** [comment]
Hello again @kenodressel, I have included the custom hook for `useAeternitySDK`. I look forward to your feedback

**Comment by emmanuelJet** [comment]
Hello @kenodressel,

> Hello again @kenodressel, I have included the custom hook for `useAeternitySDK`. I look forward to your feedback

This is to follow up on my previous comment (The quoted comment).

Thanks.

**Comment by kenodressel** [comment]
So how can I use the hook? Its not returing anything and automatically fetching the balance everytime. Please stick to the provided interface: `const [client, clientReady] = useAeternitySDK()` although you can feel free to omit the `clientReady`.

**Comment by emmanuelJet** [comment]
> So how can I use the hook? Its not returing anything and automatically fetching the balance everytime. Please stick to the provided interface: `const [client, clientReady] = useAeternitySDK()` although you can feel free to omit the `clientReady`.

Fixed, @kenodressel.

**Comment by kenodressel** [comment]
Can we remove the `window.confirm`?
Also lets move the https://github.com/emmanuelJet/aepp-boilerplate-react/blob/main/src/hooks/useAeternitySDK.js#L15-L21 to the App.js

**Comment by emmanuelJet** [comment]
Hello @kenodressel, I have removed the window.confirm. For the L15-L21, if moved to App.js, the code will be similar to one of the previous commits. Below is the App.js code snippet.

```js
import { AmountFormatter } from '@aeternity/aepp-sdk';

import './App.css';
import logo from './logo.svg';
import useAeternitySDK from './hooks/useAeternitySDK';

const App = () => {
 const client = useAeternitySDK();

 const fetchAccount = async (sdk) => {
	let address = await sdk.address();
	let balance = await sdk.balance(address, {
		format: AmountFormatter.AE_AMOUNT_FORMATS.AE
	});

	console.log("Current Address:", address);
	console.log("Current Balance:", balance + AmountFormatter.AE_AMOUNT_FORMATS.AE);	
 }

 if (client) fetchAccount(client);

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
		{
			client
			? "See console for the connected account details"
			: "Account not connected"
		}
	</p>
        <a
          className="App-link"
          href="https://aeternity.com/awesome-aeternity"
          target="_blank"
          rel="noopener noreferrer"
        >
		awesome æternity
        </a>
      </header>
    </div>
  );
};

export default App;
```

Do you want me to proceed with this?

**Comment by emmanuelJet** [comment]
@kenodressel, I look forward to your feedback.

**Comment by kenodressel** [comment]
Yes looks good but now its a bit more clearly seperated :)

**Comment by emmanuelJet** [comment]
Thanks for the feedback. However, I am finding it difficult to understand, "... but now its a bit more clearly separated".

**Comment by kenodressel** [comment]
Its supposed to be an "and" :)

now in the App.js there is an example usecase but in the background we are searching for the wallet etc. The wallet searching can be touched by the aepp developer but otherwise he/she can just use `const client = useAeternitySDK();` and it will work :)

**Comment by emmanuelJet** [comment]
Hello again @kenodressel, I have pushed the [commit](https://github.com/emmanuelJet/aepp-boilerplate-react/tree/5a708bd57e49bd512b2a0cf4fd39c5706d866cbb).

**Comment by emmanuelJet** [comment]
Good morning @kenodressel, any update?

**Comment by kenodressel** [comment]
yes sounds good, consider this bounty done.

**Comment by marc0olo** [comment]
thanks for your contribution @emmanuelJet! :)

**Comment by ErkanKanden** [comment]
@emmanuelJet here is your bounty reward :)
https://explorer.aeternity.io/transactions/th_RCtQ7K4L3P2uydtnZAo8ybqTb7bsQtuCy94Gjm8V495GqQ6y6
